// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvxGod9S4hkPtCIzDLcXhtWlo83lwWCnw',
    appId: '1:686028471869:web:d4d53a5daaa97da3b63454',
    messagingSenderId: '686028471869',
    projectId: 'flutter-210f6',
    authDomain: 'flutter-210f6.firebaseapp.com',
    storageBucket: 'flutter-210f6.firebasestorage.app',
    measurementId: 'G-HDG1SR0KTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdf52blu_a-4Io_h_hPTAyH8FCvlomSps',
    appId: '1:686028471869:android:bda517ecb34f6224b63454',
    messagingSenderId: '686028471869',
    projectId: 'flutter-210f6',
    storageBucket: 'flutter-210f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf9rOQkj74FpaT38Z2zsipOVA8hnzrnaU',
    appId: '1:686028471869:ios:8ad7c051936adfaab63454',
    messagingSenderId: '686028471869',
    projectId: 'flutter-210f6',
    storageBucket: 'flutter-210f6.firebasestorage.app',
    iosClientId: '686028471869-t9nj44lcaq8ggc279tociu63qutqf5un.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDangnhap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf9rOQkj74FpaT38Z2zsipOVA8hnzrnaU',
    appId: '1:686028471869:ios:8ad7c051936adfaab63454',
    messagingSenderId: '686028471869',
    projectId: 'flutter-210f6',
    storageBucket: 'flutter-210f6.firebasestorage.app',
    iosClientId: '686028471869-t9nj44lcaq8ggc279tociu63qutqf5un.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDangnhap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvxGod9S4hkPtCIzDLcXhtWlo83lwWCnw',
    appId: '1:686028471869:web:10f2988e3153eb8ab63454',
    messagingSenderId: '686028471869',
    projectId: 'flutter-210f6',
    authDomain: 'flutter-210f6.firebaseapp.com',
    storageBucket: 'flutter-210f6.firebasestorage.app',
    measurementId: 'G-97M3YDVS42',
  );
}
